class_name AsciiMap
extends TileMapLayer
## Map built from a text layout: one symbol per 16×16 cell, painted with the tileset of
## `legend` (see TileLegends). Ground goes on this layer; props ("decor" symbols) go on a
## child "Decor" layer over the ground of their row neighbour. Solid symbols get collision.
## Text layouts keep maps readable and diff-friendly (maps are generated by build_maps.gd).
##
## Placeholder legend (prototype maps): "." grass, "," path/floor, "#" wall, "~" water,
## "P" / "p" player spawn on grass / floor.

const TILE_SIZE := 16

## TileLegends name: "placeholder", "vila" or "junkyard".
@export var legend := "placeholder"
@export_multiline var layout := ""

## Centre of the spawn cell in local coordinates (Vector2.ZERO if the layout has none).
var spawn_position := Vector2.ZERO

var _decor: TileMapLayer
var _solid := {}  # Vector2i -> true
var _symbols := {}


func _ready() -> void:
	build(layout)


static func build_tile_set(legend_name := "placeholder") -> TileSet:
	var info := TileLegends.get_legend(legend_name)
	var set := TileSet.new()
	set.tile_size = Vector2i(TILE_SIZE, TILE_SIZE)
	set.add_physics_layer()
	var source := TileSetAtlasSource.new()
	source.texture = load(info["texture"])
	source.texture_region_size = Vector2i(TILE_SIZE, TILE_SIZE)
	set.add_source(source, 0)
	var half := TILE_SIZE / 2.0
	var square := PackedVector2Array([Vector2(-half, -half), Vector2(half, -half), Vector2(half, half), Vector2(-half, half)])
	var grid := source.get_atlas_grid_size()
	for y in grid.y:
		for x in grid.x:
			source.create_tile(Vector2i(x, y))
	for entry: Dictionary in info["symbols"].values():
		if entry.get("solid", false) and entry.has("tile"):
			var data := source.get_tile_data(entry["tile"], 0)
			if data.get_collision_polygons_count(0) == 0:
				data.add_collision_polygon(0)
				data.set_collision_polygon_points(0, 0, square)
	return set


func build(text: String) -> void:
	_symbols = TileLegends.get_legend(legend)["symbols"]
	tile_set = build_tile_set(legend)
	if _decor == null:
		_decor = TileMapLayer.new()
		_decor.name = "Decor"
		add_child(_decor)
	_decor.tile_set = tile_set
	clear()
	_decor.clear()
	_solid.clear()
	var rows := text.strip_edges().split("\n")
	for y in rows.size():
		var row := rows[y].strip_edges(false, true)
		for x in row.length():
			var symbol := row[x]
			if not _symbols.has(symbol):
				continue
			var entry: Dictionary = _symbols[symbol]
			var cell := Vector2i(x, y)
			if entry.get("decor", false):
				var ground := _ground_tile(row, x)
				if ground.x >= 0:
					set_cell(cell, 0, ground)
				if entry.has("tile"):
					_decor.set_cell(cell, 0, entry["tile"])
			else:
				set_cell(cell, 0, entry["tile"])
			if entry.get("solid", false):
				_solid[cell] = true
			if entry.get("spawn", false):
				spawn_position = map_to_local(cell)


## Ground under a prop: the nearest walkable ground symbol on the row (left first, then
## right), else the legend's "." ground.
func _ground_tile(row: String, x: int) -> Vector2i:
	for dx in range(1, row.length()):
		for nx in [x - dx, x + dx]:
			if nx < 0 or nx >= row.length():
				continue
			var entry: Dictionary = _symbols.get(row[nx], {})
			if entry.has("tile") and not entry.get("decor", false) and not entry.get("solid", false):
				return entry["tile"]
	var fallback: Dictionary = _symbols.get(".", {})
	return fallback.get("tile", Vector2i(-1, -1))


## Map bounds in pixels, for camera limits.
func pixel_rect() -> Rect2i:
	var used := get_used_rect()
	return Rect2i(used.position * TILE_SIZE, used.size * TILE_SIZE)


func is_solid_at(cell: Vector2i) -> bool:
	return _solid.has(cell)
