extends GutTest
## Prologue maps (generated by tools/build_maps.gd): every door leads to an existing map
## and spawn, every cutscene actor exists on the map that plays it, and the opening
## sequence (morning → delivery → Gerd joins) works with the real data.

const DIR := "res://scenes/maps/prologue/"
const MAPS := ["oficina", "loja", "estalagem", "relojoaria", "vila_caldeira", "estrada_sul",
	"ferro_velho_1", "ferro_velho_2", "ferro_velho_3", "camara"]

var _saved_state: Dictionary


func before_each() -> void:
	_saved_state = GameState.to_dict()
	Settings.text_speed = &"instant"
	Settings.apply()


func after_each() -> void:
	var box := DialogueManager.box()
	for i in 30:
		if not box.is_open():
			break
		box.confirm()
	GameState.from_dict(_saved_state)
	get_tree().paused = false


## Waits (bounded) for a conversation to start, then clicks through it.
func _talk_through(choice := 0) -> void:
	var box := DialogueManager.box()
	for i in 90:
		if box.is_open():
			break
		await wait_process_frames(2)
	for i in 60:
		await wait_process_frames(2)
		if not box.is_open():
			return
		if box.is_choosing():
			box.choose(choice)
		else:
			box.confirm()


func _nodes_of(scene: PackedScene) -> Dictionary:
	var state := scene.get_state()
	var nodes := {}
	for i in state.get_node_count():
		nodes[str(state.get_node_path(i)).trim_prefix("./")] = i
	return nodes


func test_every_warp_reaches_an_existing_spawn() -> void:
	for map_name: String in MAPS:
		var map: FieldMap = load(DIR + map_name + ".tscn").instantiate()
		for warp: Warp in map.find_children("*", "Warp", false, false):
			if warp.target_spawn == "":
				continue  # locked forever (north gate)
			assert_true(ResourceLoader.exists(warp.target_scene), "%s: %s" % [map_name, warp.target_scene])
			var target: PackedScene = load(warp.target_scene)
			var nodes := _nodes_of(target)
			assert_true(nodes.has("Spawns/" + warp.target_spawn),
				"%s → %s has spawn %s" % [map_name, warp.target_scene.get_file(), warp.target_spawn])
		map.free()


func test_every_map_row_has_the_same_width() -> void:
	for map_name: String in MAPS:
		var map: FieldMap = load(DIR + map_name + ".tscn").instantiate()
		var rows := (map.get_node("Map") as AsciiMap).layout.split("\n")
		for row in rows:
			assert_eq(row.length(), rows[0].length(), "%s row: %s" % [map_name, row])
		map.free()


func test_cutscene_actors_exist_on_their_maps() -> void:
	for map_name: String in MAPS:
		var map: FieldMap = load(DIR + map_name + ".tscn").instantiate()
		var cutscenes: Array[Cutscene] = []
		for trigger: CutsceneTrigger in map.find_children("*", "CutsceneTrigger", false, false):
			cutscenes.append(trigger.cutscene)
		for obj: MapObject in map.find_children("*", "MapObject", false, false):
			if obj.cutscene:
				cutscenes.append(obj.cutscene)
		for c in cutscenes:
			for step in c.steps:
				if not step.actor.is_empty():
					assert_not_null(map.get_node_or_null(step.actor), "%s: %s needs %s" % [map_name, c.id, step.actor])
		map.free()


func test_scene_changes_in_cutscenes_point_to_real_spawns() -> void:
	for path in ["res://data/cutscenes/p5_eco.tres", "res://data/cutscenes/p9_farewell.tres"]:
		var c: Cutscene = load(path)
		for step in c.steps:
			if step.type == CutsceneStep.Type.CHANGE_SCENE:
				assert_true(_nodes_of(load(step.text)).has("Spawns/" + String(step.id)), "%s → %s" % [c.id, step.id])


func test_opening_morning_delivery_and_gerd_joins() -> void:
	GameState.party.clear()
	var map: FieldMap = load(DIR + "oficina.tscn").instantiate()
	map.battle_music = false
	add_child_autofree(map)
	await wait_process_frames(3)
	await _talk_through()
	await wait_process_frames(2)
	assert_true(GameState.get_flag(&"prologue_started"))
	assert_eq(GameState.count(&"gear_box"), 1)
	assert_eq(GameState.quest_state(&"q_prologue"), "active")
	assert_eq(GameState.party.size(), 1)
	# Tobias takes the box and pays 80.
	var money := GameState.money
	var tobias: DialogueSet = load("res://data/dialogue/p_tobias.tres")
	tobias.current_branch().apply()
	assert_eq(GameState.money, money + 80)
	assert_eq(GameState.count(&"gear_box"), 0)
	assert_true(GameState.get_flag(&"delivered"))
	# Gerd joins as a guest.
	var gerd: NPC = map.get_node("GerdMorning")
	var run := func() -> void: await gerd.interact(map.player)
	run.call()
	await _talk_through()
	await wait_process_frames(4)
	await _talk_through()
	assert_true(GameState.get_flag(&"gerd_joined"))
	assert_eq(GameState.party.size(), 2)
	assert_true(GameState.party[1].data.guest)
	assert_false(gerd.visible, "Gerd leaves the room with Kael")
	assert_true(map.player.can_move())
